### ISSUE TITLE
newer setup?

### ISSUE THREAD

**Issue by cordoval** [RobustPerception/docker_examples#1]
this repo seems to have a 2 year old config for basic prometheus on docker

i am having a kubernetes cluster but trying to find how to plug my own prometheus but with persistent storage on RDS or something.

can you please do one example on how to do this?

**Comment by brian-brazil** [comment]
This repo is for examples that go with the blog posts on https://www.robustperception.io/blog/

If you can't find a useful post there you might want to try https://groups.google.com/forum/#!forum/prometheus-users
